name: CI/CD for Hard Polls Extension

on:
  push:
    branches:
      - main  # Adjust as needed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Match with your local environment version

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Run Tests
        run: npm test # Assumes you have tests set up

      - name: Package Extension
        run: |
          mkdir -p release
          zip -r release/hard-polls-extension.zip dist icons manifest.json README.md
        # Add additional files if necessary for your extension

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: hard-polls-extension.zip
        # Adjust to deploy to Chrome Web Store or GitHub Release based on your preference

      # Example GitHub Release (optional)
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: "Hard Polls v${{ github.run_number }}"
          draft: false
          prerelease: false
          files: release/hard-polls-extension.zip