name: CI/CD for Hard Polls Extension

on:
  pull_request:
    branches:
      - test
      - main
  push:
    branches:
      - test
      - main
  workflow_dispatch: # Allows manual triggers

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript with Webpack
        run: npm run build

      - name: Run Tests
        run: npm test # Replace with actual test script if available

      - name: Package Extension
        run: |
          mkdir -p release
          zip -r release/hard-polls-extension.zip dist icons manifest.json README.md
          echo "Package created successfully."
        # Add any additional files necessary for your extension package

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.actor == 'YOUR_GITHUB_USERNAME' # Replace with your GitHub username
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: hard-polls-extension.zip

      - name: Publish to Chrome Web Store
        uses: w9jds/publish-chrome-extension@v3
        with:
          extension_id: ${{ secrets.CHROME_EXTENSION_ID }}
          client_id: ${{ secrets.CHROME_CLIENT_ID }}
          client_secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh_token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          zip: ./release/hard-polls-extension.zip

      - name: Notify Deployment Success
        run: echo "Deployment to Chrome Web Store completed successfully."